! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use collectives_test, only: &
                collectives_co_sum => test_co_sum
        use intrinsics_test, only: &
                intrinsics_findloc => test_findloc
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(2)

        individual_tests(1) = collectives_co_sum()
        individual_tests(2) = intrinsics_findloc()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
